# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:03:02+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Path, Query
from pydantic import conint, constr
from starlette.requests import Request

from models import (
    MediaProcessorEnumOrder,
    MediaProcessorEnumStatus,
    MediaRecordingEnumOrder,
    MediaRecordingEnumStatus,
    MediaV1MediaProcessor,
    MediaV1MediaRecording,
    MediaV1PlayerStreamer,
    MediaV1PlayerStreamerPlayerStreamerPlaybackGrant,
    PlayerStreamerEnumOrder,
    PlayerStreamerEnumStatus,
    V1MediaProcessorsGetResponse,
    V1MediaRecordingsGetResponse,
    V1PlayerStreamersGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Media',
    version='1.42.0',
    servers=[{'url': 'https://media.twilio.com'}],
)


@app.get(
    '/v1/MediaProcessors',
    description=""" Returns a list of MediaProcessors. """,
    tags=['media_processor_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_media_processor(
    order: Optional[MediaProcessorEnumOrder] = Query(None, alias='Order'),
    status: Optional[MediaProcessorEnumStatus] = Query(None, alias='Status'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/MediaProcessors',
    tags=[
        'media_processor_management',
        'media_recording_management',
        'player_streamer_management',
        'playback_grant_management',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_media_processor(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/MediaProcessors/{Sid}',
    description=""" Returns a single MediaProcessor resource identified by a SID. """,
    tags=['playback_grant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_media_processor(
    sid: constr(pattern=r'^ZX[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/MediaProcessors/{Sid}',
    description=""" Updates a MediaProcessor resource identified by a SID. """,
    tags=['media_recording_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_media_processor(
    sid: constr(pattern=r'^ZX[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/MediaRecordings',
    description=""" Returns a list of MediaRecordings. """,
    tags=['media_recording_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_media_recording(
    order: Optional[MediaRecordingEnumOrder] = Query(None, alias='Order'),
    status: Optional[MediaRecordingEnumStatus] = Query(None, alias='Status'),
    processor_sid: Optional[
        constr(pattern=r'^ZX[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='ProcessorSid'),
    source_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='SourceSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/MediaRecordings/{Sid}',
    description=""" Deletes a MediaRecording resource identified by a SID. """,
    tags=['media_recording_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_media_recording(
    sid: constr(pattern=r'^KV[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/MediaRecordings/{Sid}',
    description=""" Returns a single MediaRecording resource identified by a SID. """,
    tags=['playback_grant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_media_recording(
    sid: constr(pattern=r'^KV[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/PlayerStreamers',
    description=""" Returns a list of PlayerStreamers. """,
    tags=['player_streamer_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_player_streamer(
    order: Optional[PlayerStreamerEnumOrder] = Query(None, alias='Order'),
    status: Optional[PlayerStreamerEnumStatus] = Query(None, alias='Status'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/PlayerStreamers',
    tags=[
        'media_processor_management',
        'media_recording_management',
        'player_streamer_management',
        'playback_grant_management',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_player_streamer(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/PlayerStreamers/{Sid}',
    description=""" Returns a single PlayerStreamer resource identified by a SID. """,
    tags=['media_processor_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_player_streamer(
    sid: constr(pattern=r'^VJ[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/PlayerStreamers/{Sid}',
    description=""" Updates a PlayerStreamer resource identified by a SID. """,
    tags=['media_recording_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_player_streamer(
    sid: constr(pattern=r'^VJ[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/PlayerStreamers/{Sid}/PlaybackGrant',
    description=""" **This method is not enabled.** Returns a single PlaybackGrant resource identified by a SID. """,
    tags=['media_processor_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_player_streamer_playback_grant(
    sid: constr(pattern=r'^VJ[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/PlayerStreamers/{Sid}/PlaybackGrant',
    tags=['media_recording_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_player_streamer_playback_grant(
    sid: constr(pattern=r'^VJ[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
