# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:03:02+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class StatusCallbackMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class MediaV1PlayerStreamerPlayerStreamerPlaybackGrant(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created this resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    grant: Optional[Any] = Field(
        None,
        description='The grant that authorizes the player sdk to connect to the livestream',
    )
    sid: Optional[
        constr(pattern=r'^VJ[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string generated to identify the PlayerStreamer resource that this PlaybackGrant authorizes views for.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class MediaProcessorEnumOrder(Enum):
    asc = 'asc'
    desc = 'desc'


class MediaProcessorEnumStatus(Enum):
    failed = 'failed'
    started = 'started'
    ended = 'ended'


class MediaProcessorEnumUpdateStatus(Enum):
    ended = 'ended'


class MediaRecordingEnumFormat(Enum):
    mp4 = 'mp4'
    webm = 'webm'


class MediaRecordingEnumOrder(Enum):
    asc = 'asc'
    desc = 'desc'


class MediaRecordingEnumStatus(Enum):
    processing = 'processing'
    completed = 'completed'
    deleted = 'deleted'
    failed = 'failed'


class PlayerStreamerEnumEndedReason(Enum):
    ended_via_api = 'ended-via-api'
    max_duration_exceeded = 'max-duration-exceeded'
    stream_disconnected_by_source = 'stream-disconnected-by-source'
    unexpected_failure = 'unexpected-failure'


class PlayerStreamerEnumOrder(Enum):
    asc = 'asc'
    desc = 'desc'


class PlayerStreamerEnumStatus(Enum):
    created = 'created'
    started = 'started'
    ended = 'ended'
    failed = 'failed'


class PlayerStreamerEnumUpdateStatus(Enum):
    ended = 'ended'


class Meta(BaseModel):
    first_page_url: Optional[AnyUrl] = None
    key: Optional[str] = None
    next_page_url: Optional[AnyUrl] = None
    page: Optional[int] = None
    page_size: Optional[int] = None
    previous_page_url: Optional[AnyUrl] = None
    url: Optional[AnyUrl] = None


class V1MediaProcessorsPostRequest(BaseModel):
    Extension: str = Field(
        ...,
        description='The [Media Extension](/docs/live/api/media-extensions-overview) name or URL. Ex: `video-composer-v2`',
    )
    ExtensionContext: str = Field(
        ...,
        description='The context of the Media Extension, represented as a JSON dictionary. See the documentation for the specific [Media Extension](/docs/live/api/media-extensions-overview) you are using for more information about the context to send.',
    )
    ExtensionEnvironment: Optional[Any] = Field(
        None,
        description='User-defined environment variables for the Media Extension, represented as a JSON dictionary of key/value strings. See the documentation for the specific [Media Extension](/docs/live/api/media-extensions-overview) you are using for more information about whether you need to provide this.',
    )
    MaxDuration: Optional[int] = Field(
        None,
        description='The maximum time, in seconds, that the MediaProcessor can run before automatically ends. The default value is 300 seconds, and the maximum value is 90000 seconds. Once this maximum duration is reached, Twilio will end the MediaProcessor, regardless of whether media is still streaming.',
    )
    StatusCallback: Optional[AnyUrl] = Field(
        None,
        description='The URL to which Twilio will send asynchronous webhook requests for every MediaProcessor event. See [Status Callbacks](/docs/live/status-callbacks) for details.',
    )
    StatusCallbackMethod_1: Optional[StatusCallbackMethod] = Field(
        None,
        alias='StatusCallbackMethod',
        description='The HTTP method Twilio should use to call the `status_callback` URL. Can be `POST` or `GET` and the default is `POST`.',
    )


class V1MediaProcessorsSidPostRequest(BaseModel):
    Status: MediaProcessorEnumUpdateStatus = Field(
        ..., description='The status of the MediaProcessor. Can be `ended`.'
    )


class V1PlayerStreamersPostRequest(BaseModel):
    MaxDuration: Optional[int] = Field(
        None,
        description='The maximum time, in seconds, that the PlayerStreamer is active (`created` or `started`) before automatically ends. The default value is 300 seconds, and the maximum value is 90000 seconds. Once this maximum duration is reached, Twilio will end the PlayerStreamer, regardless of whether media is still streaming.',
    )
    StatusCallback: Optional[AnyUrl] = Field(
        None,
        description='The URL to which Twilio will send asynchronous webhook requests for every PlayerStreamer event. See [Status Callbacks](/docs/live/status-callbacks) for more details.',
    )
    StatusCallbackMethod_1: Optional[StatusCallbackMethod] = Field(
        None,
        alias='StatusCallbackMethod',
        description='The HTTP method Twilio should use to call the `status_callback` URL. Can be `POST` or `GET` and the default is `POST`.',
    )
    Video: Optional[bool] = Field(
        None,
        description='Specifies whether the PlayerStreamer is configured to stream video. Defaults to `true`.',
    )


class V1PlayerStreamersSidPostRequest(BaseModel):
    Status: PlayerStreamerEnumUpdateStatus = Field(
        ...,
        description='The status the PlayerStreamer should be transitioned to. Can be: `ended`.',
    )


class V1PlayerStreamersSidPlaybackGrantPostRequest(BaseModel):
    AccessControlAllowOrigin: Optional[str] = Field(
        None,
        description='The full origin URL where the livestream can be streamed. If this is not provided, it can be streamed from any domain.',
    )
    Ttl: Optional[int] = Field(
        None,
        description='The time to live of the PlaybackGrant. Default value is 15 seconds. Maximum value is 60 seconds.',
    )


class MediaV1MediaProcessor(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the MediaProcessor resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    ended_reason: Optional[str] = Field(
        None,
        description='The reason why a MediaProcessor ended. When a MediaProcessor is in progress, will be `null`. When a MediaProcessor is completed, can be `ended-via-api`, `max-duration-exceeded`, `error-loading-extension`, `error-streaming-media` or `internal-service-error`. See [ended reasons](/docs/live/api/mediaprocessors#mediaprocessor-ended-reason-values) for more details.',
    )
    extension: Optional[str] = Field(
        None,
        description='The [Media Extension](/docs/live/api/media-extensions-overview) name or URL. Ex: `video-composer-v2`',
    )
    extension_context: Optional[str] = Field(
        None,
        description='The context of the Media Extension, represented as a JSON dictionary. See the documentation for the specific [Media Extension](/docs/live/api/media-extensions-overview) you are using for more information about the context to send.',
    )
    max_duration: Optional[int] = Field(
        None,
        description='The maximum time, in seconds, that the MediaProcessor can run before automatically ends. The default value is 300 seconds, and the maximum value is 90000 seconds. Once this maximum duration is reached, Twilio will end the MediaProcessor, regardless of whether media is still streaming.',
    )
    sid: Optional[
        constr(pattern=r'^ZX[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string generated to identify the MediaProcessor resource.',
    )
    status: Optional[MediaProcessorEnumStatus] = Field(
        None,
        description='The status of the MediaProcessor. Can be: `started`, `ended` or `failed`.',
    )
    status_callback: Optional[AnyUrl] = Field(
        None,
        description='The URL to which Twilio will send asynchronous webhook requests for every MediaProcessor event. See [Status Callbacks](/docs/live/status-callbacks) for details.',
    )
    status_callback_method: Optional[StatusCallbackMethod] = Field(
        None,
        description='The HTTP method Twilio should use to call the `status_callback` URL. Can be `POST` or `GET` and the default is `POST`.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class MediaV1MediaRecording(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the MediaRecording resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    duration: Optional[int] = Field(
        None, description='The duration of the MediaRecording in seconds.'
    )
    format: Optional[MediaRecordingEnumFormat] = Field(
        None, description='The format of the MediaRecording, either `mp4` or `webm`.'
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of related resources.'
    )
    media_size: Optional[int] = Field(
        None, description='The size of the recording media in bytes.'
    )
    processor_sid: Optional[
        constr(pattern=r'^ZX[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the MediaProcessor resource which produced the MediaRecording.',
    )
    resolution: Optional[str] = Field(
        None,
        description='The dimensions of the video image in pixels expressed as columns (width) and rows (height).',
    )
    sid: Optional[
        constr(pattern=r'^KV[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string generated to identify the MediaRecording resource.',
    )
    source_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the resource that generated the original media track(s) of the MediaRecording.',
    )
    status: Optional[MediaRecordingEnumStatus] = Field(
        None,
        description='The status of the MediaRecording. Can be: `processing`, `completed`, `deleted`, or `failed`.',
    )
    status_callback: Optional[AnyUrl] = Field(
        None,
        description='The URL to which Twilio will send asynchronous webhook requests for every MediaRecording event. See [Status Callbacks](/docs/live/status-callbacks) for more details.',
    )
    status_callback_method: Optional[StatusCallbackMethod] = Field(
        None,
        description='The HTTP method Twilio should use to call the `status_callback` URL. Can be `POST` or `GET` and the default is `POST`.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')


class MediaV1PlayerStreamer(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the PlayerStreamer resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    ended_reason: Optional[PlayerStreamerEnumEndedReason] = Field(
        None,
        description='The reason why a PlayerStreamer ended. When a PlayerStreamer is in progress, will be `null`. When a PlayerStreamer is completed, can be `ended-via-api`, `max-duration-exceeded`, `stream-disconnected-by-source` or `unexpected-failure`. See [ended reasons](/docs/live/api/playerstreamers#ended-reason) for more details.',
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The URLs of related resources.'
    )
    max_duration: Optional[int] = Field(
        None,
        description='The maximum time, in seconds, that the PlayerStreamer is active (`created` or `started`) before automatically ends. The default value is 300 seconds, and the maximum value is 90000 seconds. Once this maximum duration is reached, Twilio will end the PlayerStreamer, regardless of whether media is still streaming.',
    )
    sid: Optional[
        constr(pattern=r'^VJ[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string generated to identify the PlayerStreamer resource.',
    )
    status: Optional[PlayerStreamerEnumStatus] = Field(
        None,
        description='The status of the PlayerStreamer. Can be: `created`, `started`, `ended`, or `failed`. See [status](/docs/live/api/playerstreamers#status) for more information.',
    )
    status_callback: Optional[AnyUrl] = Field(
        None,
        description='The URL to which Twilio will send asynchronous webhook requests for every PlayerStreamer event. See [Status Callbacks](/docs/live/status-callbacks) for more details.',
    )
    status_callback_method: Optional[StatusCallbackMethod] = Field(
        None,
        description='The HTTP method Twilio should use to call the `status_callback` URL. Can be `POST` or `GET` and the default is `POST`.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')
    video: Optional[bool] = Field(
        None,
        description='Specifies whether the PlayerStreamer is configured to stream video. Defaults to `true`.',
    )


class V1MediaProcessorsGetResponse(BaseModel):
    media_processors: Optional[List[MediaV1MediaProcessor]] = None
    meta: Optional[Meta] = None


class V1MediaRecordingsGetResponse(BaseModel):
    media_recordings: Optional[List[MediaV1MediaRecording]] = None
    meta: Optional[Meta] = None


class V1PlayerStreamersGetResponse(BaseModel):
    meta: Optional[Meta] = None
    player_streamers: Optional[List[MediaV1PlayerStreamer]] = None
